In [7]:
import modern_robotics as mr
import numpy as np
from closed_loop_utils import four_bar, two_arm_parallel

In [8]:
def validate_two_arm(sol, L):
    """
    Validate two-arm parallel manipulator against Modern Robotics FK.
    Returns transformation matrices of both arms at solved joint angles.
    """
    th1, th2, th3, th4 = sol
    Slist1 = np.array([[0,0,1,0,0,0], [0,0,1,0,-L,0]]).T
    Slist2 = np.array([[0,0,1,0,0,0], [0,0,1,0,-L,0]]).T
    
    M1 = np.array([[1,0,0,2*L],
                   [0,1,0,0],
                   [0,0,1,0],
                   [0,0,0,1]])
    M2 = np.array([[1,0,0,2*L],
                   [0,1,0,0],
                   [0,0,1,0],
                   [0,0,0,1]])
    
    T1 = mr.FKinSpace(M1, Slist1, [th1, th2])
    T2 = mr.FKinSpace(M2, Slist2, [th3, th4])
    
    return T1, T2

In [9]:
# Example 1: 4-bar linkage
theta1 = np.deg2rad(45)
theta2, theta3 = four_bar(theta1, 1, 1, 1, 1)
print("4-bar solution (theta2, theta3) in degrees:", np.rad2deg([theta2, theta3]))

# Example 2: Two-arm parallel manipulator
sol = two_arm_parallel(1.0, 1.0, 1.0)
print("Two-arm joint solution (th1, th2, th3, th4) in degrees:", np.rad2deg(sol))

# Validate with Modern Robotics forward kinematics
T1, T2 = validate_two_arm(sol, 1.0)
print("FK arm 1 end-effector:\n", T1)
print("FK arm 2 end-effector:\n", T2)

4-bar solution (theta2, theta3) in degrees: [-360. -315.]
Two-arm joint solution (th1, th2, th3, th4) in degrees: [ -269.99999999   629.99999999  1170.         -2430.00000002]
FK arm 1 end-effector:
 [[ 1.00000000e+00 -1.35338407e-11  0.00000000e+00  1.00000000e+00]
 [ 1.35338407e-11  1.00000000e+00  0.00000000e+00  1.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
FK arm 2 end-effector:
 [[-1.00000000e+00 -3.19064775e-10  0.00000000e+00 -1.00000000e+00]
 [ 3.19064775e-10 -1.00000000e+00  0.00000000e+00  1.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
